name: deploy
on: 
  push:
    paths-ignore:
      - '**.md'
        
env:
  CONTAINER_NAME: dexcontainer.azurecr.io/koi:develop
  CONTAINER_LOGIN_SERVER: dexcontainer.azurecr.io
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        username:  ${{ secrets.DOCKER_USERNAME}}
        password:  ${{ secrets.DOCKER_PASSWORD}}

    - run: |
        docker build . -t ${{ env.CONTAINER_NAME}}
        
    - uses: azure/docker-login@v1
      with:
        username:  ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME}}
        password:  ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD}}
        login-server: ${{ env.CONTAINER_LOGIN_SERVER}}
    - run: |
        docker push ${{ env.CONTAINER_NAME}}
